# Generated by Django 3.2.6 on 2021-08-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=40)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'personnes',
            },
        ),
    ]
